# Generated by Django 5.1.5 on 2025-01-21 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default=1, max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handinghomework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univer.student'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univer.student'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
